# Generated by Django 3.1 on 2020-08-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('stocknum', models.IntegerField()),
            ],
        ),
    ]
